#!/bin/bash

set -e

main () {
    schema="${1}"
    schema_dir="./schemas"
    mode="update"
    env="${NODE_ENV}"
    host="${DB_HOST}"
    name="${DB_NAME}"
    pass="${DB_PASS}"
    db_user="${DB_USER}"

    while getopts ":c:C" opt; do
      case $opt in
        C)
          mode="current"
          ;;
        c)
          mode="create"
          schema="${OPTARG}"
          ;;
        *)
          echo "Invalid option: -$OPTARG" >&2
          exit
          ;;
      esac
    done

    check_variables

    case "$mode" in
        current )
            get_current_schema
            ;;
        create )
            create_schema
            ;;
        update )
            update_schema
            ;;
    esac
}

check_variables () {
    if [[ -z "${host}" ]]; then
        host="localhost"
    fi

    if [[ -z "${name}" ]]; then
        name="bar_buddy"
    fi

    if [[ -z "${pass}" ]]; then
        read -sp "Set DB password:" pass
    fi

    if [[ -z "${db_user}" ]]; then
        db_user="root"
    fi

    if [[ "${env}" == "production" ]]; then
        read -p "Env is currently production. OK to update schema?(y/n):" UPDATE
        if [[ "${UPDATE}" == "n" ]]; then
            exit
        fi
    fi

    schemas=$(find "${schema_dir}" -type f -name "*.sql")
}

get_current_schema () {
    query="SELECT * FROM current_schema;"
    mysql -u "${db_user}" --password="${pass}" -h "${host}" -D "${name}" -e "${query}"
}

create_schema () {
    mkdir -p schemas
    mysqldump -u "${db_user}" --password="${pass}" -h "${host}" "${name}" --no-data \
    > schemas/$(date +%s)_"${schema}".sql
}

update_schema () {
    if [[ -z "${schema}" ]]; then
        schema=$(echo "${schemas}" | sort | head -n 1)
        execute_update
    elif [[ ! -e "${schema}" ]]; then
        echo "Selected schema is not valid"
        echo "Please choose one of the following schemas:"
        echo "${schemas}"
        exit
    else
        execute_update
    fi
}

execute_update () {
    schema_name="${schema##*[a-z]*/}"
    schema_name="${schema_name%%.*}"

    queries="CREATE TABLE IF NOT EXISTS current_schema (ID int NOT NULL, schema_name VARCHAR(50) NOT NULL, executed TIMESTAMP, PRIMARY KEY (ID));"
    queries+="REPLACE INTO current_schema (ID, schema_name) VALUES(1, '${schema_name}');"

    mysql -u "${db_user}" --password="${pass}" -h "${host}" -D "${name}" -e "${queries}"
    mysql -u "${db_user}" --password="${pass}" -h "${host}" -D "${name}" < "${schema}"
}


main "${@}"